default: &default
  protocol: 'http'
  host: db
  port: 5984
  username: admin
  password: password
  prefix: opendig

development:
  <<: *default
  suffix: development

test:
  <<: *default
  suffix: test

production:
  protocol: 'https'
  host: couchdb.rekrei.org
  port: 6984
  username: admin
  password: jugqoO9K!&Cp7jBT
  prefix: opendig
  suffix: production
